### ISSUE TITLE
minute/hour functionality of Select Time doesn't work as expected

### ISSUE THREAD

**Issue by criemen** [ripienaar/gdash#98]
Hello,
i've updated my install to the latest HEAD, and now it includes the Select Date functionality (which is great, thanks!). Unfortunately, whenever I use the widget for selecting a Datetime, and move the minute or hour slider, both the from and the until field are set to the same date, rendering the hour and minute selection useless.
The expected behauviour is obviously that only the field which has the focus is updated.

**Comment by bwhaley** [comment]
Hi,

I'm not able to reproduce this. I click on the Select Date option, then click the first field and pick a date + slider to adjust time, then click Done, then repeat for the second field, then click show, and Voila! It adds `/time/04%3A00_20130416/06%3A00_20130416` to the URL and reflects the time correctly in the graph.

**Comment by criemen** [comment]
Sorry for not answering earlier, I was on vacation:
The workflow first choosing from, then until works actually fine, I missed that when reporting the bug.
What doesn't work is afterwards adjusting the from time to an earlier (or later, but before until) time, because that sets until always to the same time which is annoying

**Comment by hamann** [comment]
Should be fixed in hamann/gdash@7441c0564572f681f8145232644b4283b642fd39

@Corni does that work for you?

**Comment by criemen** [comment]
Sorry for replying so late:
This still does not fix the issue - just play around with selecting a form date, and then playing with until.
Sometimes, setting until or leaving the dialog sets from to the chosen until value, even with the patch.
Aditionally, the same behaviour can be triggered by adjusting from - it overwrites until as well.

**Comment by criemen** [comment]
Sorry for the previous comment, I did not save the edited file, so I didn't apply the patch.
It works great, please merge this to trunk!
Thanks for your efforts :+1:
